# Variáveis Ubuntu
vscode: https://az764295.vo.msecnd.net/stable/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/code_1.32.3-1552606978_amd64.deb
chrome: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
key_virtualbox: https://www.virtualbox.org/download/oracle_vbox_2016.asc
teamviewer: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
virtualbox: virtualbox-6.0
zsh_config: https://raw.githubusercontent.com/alysonfranklin/conf_pessoal/master/.zshrc
git_config: https://raw.githubusercontent.com/alysonfranklin/conf_pessoal/master/.gitconfig
repo_neovim: https://alysonfranklin@bitbucket.org/alysonfranklin/neovim.git
tmux_conf: https://raw.githubusercontent.com/alysonfranklin/conf_pessoal/master/.tmux.conf
tmux_conf_local: https://raw.githubusercontent.com/alysonfranklin/conf_pessoal/master/.tmux.conf.local
key_teamviewer: https://download.teamviewer.com/download/linux/signature/TeamViewer2017.asc
repo_sublimetext: deb https://download.sublimetext.com/ apt/stable/
down_terraform: https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip

# Variáveis Fedora
repo_fusion: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
repo_fusion2: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm