# Variáveis Ubuntu/Debian
vscode: https://az764295.vo.msecnd.net/stable/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/code_1.32.3-1552606978_amd64.deb
chrome: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
key_virtualbox: https://www.virtualbox.org/download/oracle_vbox_2016.asc
teamviewer: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
virtualbox: https://download.virtualbox.org/virtualbox/6.0.4/virtualbox-6.0_6.0.4-128413~Ubuntu~bionic_amd64.deb
zsh_config: https://raw.githubusercontent.com/alysonfranklin/conf_pessoal/master/.zshrc
git_config: https://raw.githubusercontent.com/alysonfranklin/conf_pessoal/master/.gitconfig
reponeovim: https://github.com/alysonfranklin/neovim.git
tmux_conf: https://raw.githubusercontent.com/alysonfranklin/conf_pessoal/master/.tmux.conf
tmux_conf_local: https://raw.githubusercontent.com/alysonfranklin/conf_pessoal/master/.tmux.conf.local
key_teamviewer: https://download.teamviewer.com/download/linux/signature/TeamViewer2017.asc
repo_sublimetext: deb https://download.sublimetext.com/ apt/stable/
down_terraform: https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
config_ssh: https://raw.githubusercontent.com/alysonfranklin/conf_pessoal/master/config

# Variáveis CentOS/RHEL
repo_fusion: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
repo_fusion2: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
chrome_fedora: https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
teamviewer_fedora: https://download.teamviewer.com/download/linux/teamviewer.x86_64.rpm
virtualbox_fedora: https://download.virtualbox.org/virtualbox/6.0.0/VirtualBox-6.0-6.0.0_127566_fedora26-1.x86_64.rpm
vagrant_fedora: https://releases.hashicorp.com/vagrant/2.2.4/vagrant_2.2.4_x86_64.rpm
